// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// code.cpp
cpp11::writable::integers which_within_dist(doubles_matrix<> distmat, doubles idx, double dist);
extern "C" SEXP _spatialsample_which_within_dist(SEXP distmat, SEXP idx, SEXP dist) {
  BEGIN_CPP11
    return cpp11::as_sexp(which_within_dist(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(distmat), cpp11::as_cpp<cpp11::decay_t<doubles>>(idx), cpp11::as_cpp<cpp11::decay_t<double>>(dist)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_spatialsample_which_within_dist", (DL_FUNC) &_spatialsample_which_within_dist, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_spatialsample(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
