# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_within_dist <- function(distmat, idx, dist) {
    .Call(`_spatialsample_which_within_dist`, distmat, idx, dist)
}

